jelly_hardware:
    ### Joint configuration
    joint_names:
        - FL_hip_joint
        - FL_upper_leg_joint
        - FL_lower_leg_joint
        - FR_hip_joint
        - FR_upper_leg_joint
        - FR_lower_leg_joint
        - RL_hip_joint
        - RL_upper_leg_joint
        - RL_lower_leg_joint
        - RR_hip_joint
        - RR_upper_leg_joint
        - RR_lower_leg_joint

    odrive_ids:
        - id: 2069339B304B # Front Right
          axis1: FL_upper_leg_joint
          axis0: FL_lower_leg_joint

        - id: 2069339E304B # Rear Right
          axis0: RL_upper_leg_joint
          axis1: RL_lower_leg_joint

        - id: 206A3378304B # Rear Left
          axis1: RR_upper_leg_joint
          axis0: RR_lower_leg_joint

        - id: 206A3398304B # Front Left
          axis1: FR_upper_leg_joint
          axis0: FR_lower_leg_joint

        - id: 207C37823548 # Rear
          axis0: RL_hip_joint
          axis1: RR_hip_joint

        - id: 207C37863548 # Front
          axis0: FR_hip_joint
          axis1: FL_hip_joint


    base_link: chassis
    fl_link:   FL_lower_leg
    fr_link:   FR_lower_leg
    rl_link:   RL_lower_leg
    rr_link:   RR_lower_leg

    gear_ratio: 8.1
    joint_directions: [-1.0, 1.0, -1.0, 1.0, -1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, 1.0]
    starting_joints: [0.26, 0.0, 0.0, 0.26, 0.0, 0.0, 0.26, 0.0, 0.0, 0.26, 0.0, 0.0]

jelly_control:
    # number between 0 and 1
    speed: 0.5

    home_position:    [0.0, 0.7, -1.4, 0.0, 0.7, -1.4, 0.0, -0.7, 1.4, 0.0, -0.7, 1.4]
    rolling_position: [0.0, 1.1, -2.2, 0.0, 1.1, -2.2, 0.0, -1.1, 2.2, 0.0, -1.1, 2.2]

    total_gait_count: 500

    walking_gait:
        p1     : [1.85e-01, 4.5e-02, -3.94e-01]
        p2     : [-1.85e-01, 4.5e-02, -3.94e-01]
        offset : [0.07, 0, 0]
        beta   : 0.85

    turning_gait:
        p1     : [1.85e-01, 4.5e-02, -3.94e-01]
        p2     : [-1.85e-01, 4.5e-02, -3.94e-01]
